-- setmetatable(_G, {
--     __index = function(t, key)
--         return proxy[key]
--     end,
--     __newindex = function(t, key, value)
--         if key == "scene" then
--             print("Changed")
--             proxy[key] = value
--         end
--     end
-- })
